-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Extra autostart processes

-- exec-once = uwsm app -- my-service

-- exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

-- exec-once = systemctl --user start hyprland-session.target

-- exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

-- exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'

-- exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

-- exec-once = swaybg -i ~/.dariobf/wallpapers/wallhaven-framework.jpg -m fill





-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("noctalia")
    hl.exec_cmd("firefox")
    -- Aplica la distribución de workspaces por monitor según haya o no dock/lid.
    -- clamshell.sh reload detecta el estado y llama a open/close, fijando reglas
    -- persistentes; así el layout es correcto ya desde el login, no solo al abrir/cerrar la tapa.
    hl.exec_cmd(os.getenv("HOME") .. "/.config/hypr/scripts/clamshell.sh reload")
end)
