-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
        before_sleep_cmd = "pidof hyprlock || hyprlock",
        after_sleep_cmd = "hyprctl dispatch dpms on",
        inhibit_sleep = true,
    },
})

-- listener {

--     timeout = 330                                            # 5.5min

--     on-timeout = hyprctl dispatch dpms off                   # screen off

--     on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen on

-- }

hl.config({
    listener = {
        event = "lid_close",
        on_status_change = "systemctl suspend",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output

hl.config({
    listener = {
        event = "lid_open",
        on_status_change = "hyprctl dispatch dpms on",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output
