general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = true  
}

listener {
    timeout = 330                                            # 5.5min
    on-timeout = hyprctl dispatch dpms off                   # screen off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen on
}

listener {
    event = lid_close
    on-status-change = systemctl suspend
}

listener {
    event = lid_open
    on-status-change = hyprctl dispatch dpms on
}
