-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Control your input devices

-- See https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        -- Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
        -- kb_layout = us,dk
        kb_options = "compose:caps",
        -- ,grp:alts_toggle
        kb_layout = "us",
        kb_variant = "altgr-intl",
        -- Change speed of keyboard repeat
        repeat_rate = 40,
        repeat_delay = 600,
        -- Increase sensitity for mouse/trackpack (default: 0)
        -- sensitivity = 0.35
        touchpad = {
            -- Use natural (inverse) scrolling
            -- natural_scroll = true
            -- Use two-finger clicks for right-click instead of lower-right corner
            -- clickfinger_behavior = true
            -- Control the speed of your scrolling
            scroll_factor = 0.4,
        },
    },
})

-- Scroll faster in the terminal

hl.window_rule({
    name  = "windowrule-1",
    match = {
        tag = terminal,
    },
    scroll_touchpad = 1.5,
})
